/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import CodigoQR.QRCodigos;
import ConexionMySQL.Conexion;
import ConexionMySQL.GuardarDatosTablas;
import Controles.ControlLimites;
import Controles.ControlListaVentas;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author HP
 */
public class ListaVentas extends javax.swing.JPanel {

    ControlListaVentas clv = new ControlListaVentas();
    private GuardarDatosTablas gdt = new GuardarDatosTablas();
    private Conexion con = new Conexion();

    public ListaVentas() throws SQLException {
        initComponents();
        this.ControlLimites();
        this.gdt.GuardarDatosFactura();
        this.tblVentas.setModel(this.gdt.MostrarDatosFacturas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        tituloCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        titulofecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        fondobtnBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JLabel();
        fondobtnEliminar = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JLabel();
        fondoQR = new javax.swing.JPanel();
        QR = new javax.swing.JLabel();
        fondobtnGenerarQR = new javax.swing.JPanel();
        btnGenerarQR = new javax.swing.JLabel();
        lblCambiante = new javax.swing.JLabel();
        fondoVentas = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVentas.setBackground(new java.awt.Color(255, 255, 255));
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tblVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 420, 350));

        tituloCodigo.setForeground(new java.awt.Color(0, 0, 0));
        tituloCodigo.setText("BUSCAR POR CODIGO:");
        jPanel1.add(tituloCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 140, 20));

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 140, -1));

        titulofecha.setForeground(new java.awt.Color(0, 0, 0));
        titulofecha.setText("BUSCAR POR FECHA:");
        jPanel1.add(titulofecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 130, 30));

        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 140, -1));

        fondobtnBuscar.setBackground(new java.awt.Color(255, 255, 255));

        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("BUSCAR");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondobtnBuscarLayout = new javax.swing.GroupLayout(fondobtnBuscar);
        fondobtnBuscar.setLayout(fondobtnBuscarLayout);
        fondobtnBuscarLayout.setHorizontalGroup(
            fondobtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(fondobtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondobtnBuscarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        fondobtnBuscarLayout.setVerticalGroup(
            fondobtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(fondobtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondobtnBuscarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(fondobtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 140, 40));

        fondobtnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        fondobtnEliminar.setPreferredSize(new java.awt.Dimension(60, 60));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondobtnEliminarLayout = new javax.swing.GroupLayout(fondobtnEliminar);
        fondobtnEliminar.setLayout(fondobtnEliminarLayout);
        fondobtnEliminarLayout.setHorizontalGroup(
            fondobtnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(fondobtnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondobtnEliminarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnEliminar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        fondobtnEliminarLayout.setVerticalGroup(
            fondobtnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(fondobtnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondobtnEliminarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnEliminar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(fondobtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 60, 60));

        fondoQR.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fondoQRLayout = new javax.swing.GroupLayout(fondoQR);
        fondoQR.setLayout(fondoQRLayout);
        fondoQRLayout.setHorizontalGroup(
            fondoQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QR, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        fondoQRLayout.setVerticalGroup(
            fondoQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QR, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel1.add(fondoQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 130, 130));

        fondobtnGenerarQR.setBackground(new java.awt.Color(255, 255, 255));

        btnGenerarQR.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerarQR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGenerarQR.setText("GENERAR QR");
        btnGenerarQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarQR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarQRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarQRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarQRMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fondobtnGenerarQRLayout = new javax.swing.GroupLayout(fondobtnGenerarQR);
        fondobtnGenerarQR.setLayout(fondobtnGenerarQRLayout);
        fondobtnGenerarQRLayout.setHorizontalGroup(
            fondobtnGenerarQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGenerarQR, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        fondobtnGenerarQRLayout.setVerticalGroup(
            fondobtnGenerarQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGenerarQR, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(fondobtnGenerarQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 90, 40));
        jPanel1.add(lblCambiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 420, 30));

        fondoVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoListaCompras.png"))); // NOI18N
        jPanel1.add(fondoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        this.fondobtnBuscar.setBackground(Color.blue);
        this.btnBuscar.setForeground(Color.white);
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        this.fondobtnBuscar.setBackground(Color.white);
        this.btnBuscar.setForeground(Color.black);
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        this.fondobtnEliminar.setBackground(Color.blue);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        this.fondobtnEliminar.setBackground(Color.white);
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnGenerarQRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarQRMouseEntered
        this.fondobtnGenerarQR.setBackground(Color.blue);
        this.btnGenerarQR.setForeground(Color.white);
    }//GEN-LAST:event_btnGenerarQRMouseEntered

    private void btnGenerarQRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarQRMouseExited
        this.fondobtnGenerarQR.setBackground(Color.white);
        this.btnGenerarQR.setForeground(Color.black);
    }//GEN-LAST:event_btnGenerarQRMouseExited

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        if (this.con.BuscarConexion()) {
            JOptionPane.showMessageDialog(null, "No hay conexion con la base");
        } else {
            if (this.txtCodigo.getText().isEmpty()) {
                if (this.txtFecha.getText().isEmpty()) {
                    this.lblCambiante.setForeground(Color.red);
                    this.lblCambiante.setText("LLENE UN CAMPO");
                } else {
                    if (this.clv.ControlFecha(this.txtFecha.getText(), this.lblCambiante)) {
                        try {
                            this.clv.GuardarVentasFecha(this.txtFecha.getText());
                            this.tblVentas.setModel(this.clv.MostrarDatosVentas());
                            this.lblCambiante.setText("");
                            this.txtCodigo.setText("");
                            this.txtFecha.setText("");
                        } catch (SQLException ex) {
                            Logger.getLogger(ListaCompras.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            } else {
                if (this.txtFecha.getText().isEmpty()) {
                    if (this.clv.ControlCodigo(this.txtCodigo.getText(), this.lblCambiante)) {
                        try {
                            this.clv.GuardarVentaCodigo(this.txtCodigo.getText());
                            this.tblVentas.setModel(this.clv.MostrarDatosVentas());
                            this.lblCambiante.setText("");
                            this.txtCodigo.setText("");
                            this.txtFecha.setText("");
                        } catch (SQLException ex) {
                            Logger.getLogger(ListaCompras.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } else {
                    if (this.clv.ControlCodigo(this.txtCodigo.getText(), this.lblCambiante) && this.clv.ControlFecha(this.txtFecha.getText(), this.lblCambiante)) {
                        try {
                            this.clv.GuardarVentaCodigoFecha(this.txtCodigo.getText(), this.txtFecha.getText());
                            this.tblVentas.setModel(this.clv.MostrarDatosVentas());
                            this.lblCambiante.setText("");
                            this.txtCodigo.setText("");
                            this.txtFecha.setText("");
                        } catch (SQLException ex) {
                            Logger.getLogger(ListaCompras.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
            try {
                this.con.Desconectar();
            } catch (SQLException ex) {
                Logger.getLogger(ListaVentas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int filasseleccionadas = this.tblVentas.getSelectedRow();
        if (filasseleccionadas != -1) {
            String codigo = (String) this.tblVentas.getValueAt(filasseleccionadas, 0);
            String fecha = String.valueOf(this.tblVentas.getValueAt(filasseleccionadas, 1));
            try {
                if (this.con.BuscarConexion()) {
                    JOptionPane.showMessageDialog(null, "No hay conexion con la base");
                } else {
                    this.clv.Eliminar(codigo, String.valueOf(LocalDate.now()), this.lblCambiante);
                    this.gdt.GuardarDatosFactura();
                    this.tblVentas.setModel(gdt.MostrarDatosFacturas());
                    this.txtCodigo.setText("");
                    this.txtFecha.setText("");
                    this.con.Desconectar();
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuCiudades.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.lblCambiante.setForeground(Color.red);
            this.lblCambiante.setText("Seleccione una Venta");
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnGenerarQRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarQRMouseClicked
        int filasseleccionadas = this.tblVentas.getSelectedRow();
        if (filasseleccionadas != -1) {
            String codigoCompra = (String) this.tblVentas.getValueAt(filasseleccionadas, 0);
            String fecha = String.valueOf(this.tblVentas.getValueAt(filasseleccionadas, 1));
            String Proveedor = (String) this.tblVentas.getValueAt(filasseleccionadas, 2);
            String total = String.valueOf(this.tblVentas.getValueAt(filasseleccionadas, 3));
            QRCodigos qr = new QRCodigos();
            this.QR.setIcon(qr.GenerarCodigoQRFactura(codigoCompra, fecha, Proveedor, total + "$"));
            this.lblCambiante.setText("");
        } else {
            this.lblCambiante.setForeground(Color.red);
            this.lblCambiante.setText("Seleccione una Factura");
        }
    }//GEN-LAST:event_btnGenerarQRMouseClicked
    public void ControlLimites() {
        ((AbstractDocument) this.txtCodigo.getDocument()).setDocumentFilter(new ControlLimites(10));
        ((AbstractDocument) this.txtFecha.getDocument()).setDocumentFilter(new ControlLimites(10));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QR;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGenerarQR;
    private javax.swing.JPanel fondoQR;
    private javax.swing.JLabel fondoVentas;
    private javax.swing.JPanel fondobtnBuscar;
    private javax.swing.JPanel fondobtnEliminar;
    private javax.swing.JPanel fondobtnGenerarQR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCambiante;
    private javax.swing.JTable tblVentas;
    private javax.swing.JLabel tituloCodigo;
    private javax.swing.JLabel titulofecha;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
