/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import ConexionMySQL.Conexion;
import ConexionMySQL.GuardarDatosTablas;
import Controles.ControlLimites;
import Controles.ControlProvincia;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

public class MenuProvincias extends javax.swing.JPanel {

    private GuardarDatosTablas gdt = new GuardarDatosTablas();
    private ControlProvincia cp = new ControlProvincia();
    Conexion con = new Conexion();

    public MenuProvincias() throws SQLException {
        initComponents();
        this.FondoOpciones.setVisible(false);
        this.gdt.GuardarProvincia();
        this.tblProvincias.setModel(gdt.MostrarDatosProvincias());
        this.ControlLimites();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFondoTotal = new javax.swing.JPanel();
        FondoBtnAñadir = new javax.swing.JPanel();
        BtnAñadir = new javax.swing.JLabel();
        FondoBtnModificar = new javax.swing.JPanel();
        BtnModificar = new javax.swing.JLabel();
        FondoBtnEliminar = new javax.swing.JPanel();
        BtnEliminar = new javax.swing.JLabel();
        FondoOpciones = new javax.swing.JPanel();
        tituloIngreseNuevoNombre = new javax.swing.JLabel();
        txtNuevoNombre = new javax.swing.JTextField();
        tituloIngreseNuevoCodigo = new javax.swing.JLabel();
        txtNuevoCodigo = new javax.swing.JTextField();
        FondobtnAccion = new javax.swing.JPanel();
        BtnAccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProvincias = new javax.swing.JTable();
        textoCambiante = new javax.swing.JLabel();
        lblFondoProvincias = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFondoTotal.setBackground(new java.awt.Color(0, 0, 0));
        lblFondoTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBtnAñadir.setBackground(new java.awt.Color(255, 255, 255));

        BtnAñadir.setBackground(new java.awt.Color(0, 0, 0));
        BtnAñadir.setForeground(new java.awt.Color(0, 0, 0));
        BtnAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAñadir.setText("AÑADIR NUEVA PROVINCIA");
        BtnAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAñadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAñadirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FondoBtnAñadirLayout = new javax.swing.GroupLayout(FondoBtnAñadir);
        FondoBtnAñadir.setLayout(FondoBtnAñadirLayout);
        FondoBtnAñadirLayout.setHorizontalGroup(
            FondoBtnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        FondoBtnAñadirLayout.setVerticalGroup(
            FondoBtnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lblFondoTotal.add(FondoBtnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 190, 40));

        FondoBtnModificar.setBackground(new java.awt.Color(255, 255, 255));

        BtnModificar.setBackground(new java.awt.Color(102, 102, 102));
        BtnModificar.setForeground(new java.awt.Color(0, 0, 0));
        BtnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnModificar.setText("MODIFICAR PROVINCIA");
        BtnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FondoBtnModificarLayout = new javax.swing.GroupLayout(FondoBtnModificar);
        FondoBtnModificar.setLayout(FondoBtnModificarLayout);
        FondoBtnModificarLayout.setHorizontalGroup(
            FondoBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        FondoBtnModificarLayout.setVerticalGroup(
            FondoBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lblFondoTotal.add(FondoBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        FondoBtnEliminar.setBackground(new java.awt.Color(255, 255, 255));

        BtnEliminar.setBackground(new java.awt.Color(102, 102, 102));
        BtnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        BtnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnEliminar.setText("ELIMINAR PROVINCIA");
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FondoBtnEliminarLayout = new javax.swing.GroupLayout(FondoBtnEliminar);
        FondoBtnEliminar.setLayout(FondoBtnEliminarLayout);
        FondoBtnEliminarLayout.setHorizontalGroup(
            FondoBtnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        FondoBtnEliminarLayout.setVerticalGroup(
            FondoBtnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lblFondoTotal.add(FondoBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        FondoOpciones.setBackground(new java.awt.Color(255, 255, 255));

        tituloIngreseNuevoNombre.setForeground(new java.awt.Color(0, 0, 0));
        tituloIngreseNuevoNombre.setText("Ingrese el nuevo nombre:");

        txtNuevoNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNuevoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoNombreActionPerformed(evt);
            }
        });

        tituloIngreseNuevoCodigo.setForeground(new java.awt.Color(0, 0, 0));
        tituloIngreseNuevoCodigo.setText("Ingrese el nuevo codigo:");

        txtNuevoCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtNuevoCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        FondobtnAccion.setBackground(new java.awt.Color(255, 255, 255));

        BtnAccion.setBackground(new java.awt.Color(102, 102, 102));
        BtnAccion.setForeground(new java.awt.Color(0, 0, 0));
        BtnAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnAccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAccionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FondobtnAccionLayout = new javax.swing.GroupLayout(FondobtnAccion);
        FondobtnAccion.setLayout(FondobtnAccionLayout);
        FondobtnAccionLayout.setHorizontalGroup(
            FondobtnAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnAccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
        FondobtnAccionLayout.setVerticalGroup(
            FondobtnAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondobtnAccionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout FondoOpcionesLayout = new javax.swing.GroupLayout(FondoOpciones);
        FondoOpciones.setLayout(FondoOpcionesLayout);
        FondoOpcionesLayout.setHorizontalGroup(
            FondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoOpcionesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(FondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloIngreseNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloIngreseNuevoNombre))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(FondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FondobtnAccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        FondoOpcionesLayout.setVerticalGroup(
            FondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloIngreseNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloIngreseNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FondobtnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );

        lblFondoTotal.add(FondoOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 330, 120));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tblProvincias.setBackground(new java.awt.Color(255, 255, 255));
        tblProvincias.setForeground(new java.awt.Color(0, 0, 0));
        tblProvincias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProvincias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblProvincias.setGridColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tblProvincias);

        lblFondoTotal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 580, 220));

        textoCambiante.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textoCambiante.setForeground(new java.awt.Color(255, 51, 51));
        lblFondoTotal.add(textoCambiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 330, 27));

        lblFondoProvincias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoProvincia_1.jpg"))); // NOI18N
        lblFondoTotal.add(lblFondoProvincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        add(lblFondoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoNombreActionPerformed

    private void BtnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAñadirMouseClicked
        this.FondoOpciones.setVisible(true);
        this.tituloIngreseNuevoCodigo.setText("Ingrese el nuevo codigo:");
        this.tituloIngreseNuevoCodigo.setVisible(true);
        this.txtNuevoCodigo.setVisible(true);
        this.txtNuevoCodigo.setText("");
        this.tituloIngreseNuevoNombre.setVisible(true);
        this.txtNuevoNombre.setVisible(true);
        this.txtNuevoNombre.setText("");
        this.BtnAccion.setText("AÑADIR");
        this.BtnAccion.setVisible(true);
        this.textoCambiante.setText("");
    }//GEN-LAST:event_BtnAñadirMouseClicked

    private void BtnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseClicked
        this.FondoOpciones.setVisible(true);
        this.textoCambiante.setText("");
        this.tituloIngreseNuevoCodigo.setVisible(false);
        this.txtNuevoCodigo.setVisible(false);
        this.txtNuevoCodigo.setText("");
        this.tituloIngreseNuevoNombre.setVisible(true);
        this.txtNuevoNombre.setVisible(true);
        this.txtNuevoNombre.setText("");
        this.BtnAccion.setText("MODIFICAR");
        this.BtnAccion.setVisible(true);
    }//GEN-LAST:event_BtnModificarMouseClicked

    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
        this.FondoOpciones.setVisible(false);
        this.textoCambiante.setText("");
        this.tituloIngreseNuevoCodigo.setVisible(false);
        this.txtNuevoCodigo.setVisible(false);
        this.txtNuevoCodigo.setText("");
        this.tituloIngreseNuevoNombre.setVisible(false);
        this.txtNuevoNombre.setVisible(false);
        this.txtNuevoNombre.setText("");
        this.BtnAccion.setText("ELIMINAR");
        this.BtnAccion.setVisible(false);
        int filasseleccionadas = this.tblProvincias.getSelectedRow();
        if (filasseleccionadas != -1) {
            String codigo = (String) this.tblProvincias.getValueAt(filasseleccionadas, 0);
            try {
                if (this.con.BuscarConexion()) {
                    JOptionPane.showMessageDialog(null, "No hay conexion con la base");
                } else {
                    this.cp.Eliminar(codigo, this.textoCambiante);
                    this.gdt.GuardarProvincia();
                    this.tblProvincias.setModel(gdt.MostrarDatosProvincias());
                    this.cp.getCon().Desconectar();
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuProvincias.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.textoCambiante.setForeground(new Color(255, 51, 51));
            this.textoCambiante.setText("Seleccione una fila");
        }
    }//GEN-LAST:event_BtnEliminarMouseClicked

    private void BtnAccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAccionMouseClicked
        if (this.con.BuscarConexion()) {
            JOptionPane.showMessageDialog(null, "No hay conexion con la base");
        } else {
            if (this.BtnAccion.getText().equals("AÑADIR")) {

                try {
                    cp.AgregarProvincia(this.txtNuevoCodigo.getText(), this.txtNuevoNombre.getText(), this.textoCambiante);
                    this.gdt.GuardarProvincia();
                    this.tblProvincias.setModel(gdt.MostrarDatosProvincias());
                    this.txtNuevoNombre.setText("");
                    this.txtNuevoCodigo.setText("");
                    this.cp.getCon().Desconectar();
                } catch (SQLException ex) {
                    Logger.getLogger(MenuProvincias.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.txtNuevoCodigo.setText("");
                this.txtNuevoNombre.setText("");
            }
            if (this.BtnAccion.getText().equals("MODIFICAR")) {
                int filasseleccionadas = this.tblProvincias.getSelectedRow();
                if (filasseleccionadas != -1) {
                    String codigo = (String) this.tblProvincias.getValueAt(filasseleccionadas, 0);
                    try {
                        this.cp.ModificarProvincia(this.txtNuevoNombre.getText(), codigo, this.textoCambiante);
                        this.gdt.GuardarProvincia();
                        this.tblProvincias.setModel(gdt.MostrarDatosProvincias());
                        this.txtNuevoNombre.setText("");
                        this.txtNuevoCodigo.setText("");
                        this.cp.getCon().Desconectar();
                    } catch (SQLException ex) {
                        Logger.getLogger(MenuProvincias.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    this.textoCambiante.setForeground(new Color(255, 51, 51));
                    this.textoCambiante.setText("Seleccione una fila");
                }
            }
        }
    }//GEN-LAST:event_BtnAccionMouseClicked

    private void BtnAñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAñadirMouseEntered
        this.FondoBtnAñadir.setBackground(Color.blue);
        this.BtnAñadir.setForeground(Color.white);
    }//GEN-LAST:event_BtnAñadirMouseEntered

    private void BtnAñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAñadirMouseExited
        this.FondoBtnAñadir.setBackground(Color.white);
        this.BtnAñadir.setForeground(Color.black);
    }//GEN-LAST:event_BtnAñadirMouseExited

    private void BtnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseEntered
        this.FondoBtnModificar.setBackground(Color.blue);
        this.BtnModificar.setForeground(Color.white);
    }//GEN-LAST:event_BtnModificarMouseEntered

    private void BtnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseExited
        this.FondoBtnModificar.setBackground(Color.white);
        this.BtnModificar.setForeground(Color.black);
    }//GEN-LAST:event_BtnModificarMouseExited

    private void BtnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseEntered
        this.FondoBtnEliminar.setBackground(Color.blue);
        this.BtnEliminar.setForeground(Color.white);
    }//GEN-LAST:event_BtnEliminarMouseEntered

    private void BtnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseExited
        this.FondoBtnEliminar.setBackground(Color.white);
        this.BtnEliminar.setForeground(Color.black);
    }//GEN-LAST:event_BtnEliminarMouseExited

    private void BtnAccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAccionMouseEntered
        this.FondobtnAccion.setBackground(Color.blue);
        this.BtnAccion.setForeground(Color.white);
    }//GEN-LAST:event_BtnAccionMouseEntered

    private void BtnAccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAccionMouseExited
        this.FondobtnAccion.setBackground(Color.white);
        this.BtnAccion.setForeground(Color.black);
    }//GEN-LAST:event_BtnAccionMouseExited
    public void ControlLimites() {
        ((AbstractDocument) this.txtNuevoCodigo.getDocument()).setDocumentFilter(new ControlLimites(5));
        ((AbstractDocument) this.txtNuevoNombre.getDocument()).setDocumentFilter(new ControlLimites(50));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAccion;
    private javax.swing.JLabel BtnAñadir;
    private javax.swing.JLabel BtnEliminar;
    private javax.swing.JLabel BtnModificar;
    private javax.swing.JPanel FondoBtnAñadir;
    private javax.swing.JPanel FondoBtnEliminar;
    private javax.swing.JPanel FondoBtnModificar;
    private javax.swing.JPanel FondoOpciones;
    private javax.swing.JPanel FondobtnAccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondoProvincias;
    private javax.swing.JPanel lblFondoTotal;
    private javax.swing.JTable tblProvincias;
    private javax.swing.JLabel textoCambiante;
    private javax.swing.JLabel tituloIngreseNuevoCodigo;
    private javax.swing.JLabel tituloIngreseNuevoNombre;
    private javax.swing.JTextField txtNuevoCodigo;
    private javax.swing.JTextField txtNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
